apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: NodePort
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30861