apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_URL
              value: http://eureka-service:8761/eureka/
          readinessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8081
            initialDelaySeconds: 8
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: "/actuator/health"
              port: 8081
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3