server:
  port: 8082
  undertow:
    options:
      KEEP_ALIVE: false
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
