server:
  port: 8082
  undertow:
    options:
      KEEP_ALIVE: false
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    metadata-map:
      management.port: ${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  info:
    app:
      name: User Service
      description: This is the user microservice
      version: 1.0.0