name: Deploy Order Service to Minikube

on:
  push:
    paths:
      - 'order-service/**'
      - '.github/workflows/deploy-order.yml'
    branches:
      - kubernates-deployment-fix

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Local runner with minikube & docker installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build order-service JAR
        run: |
          cd order-service
          mvn clean package -DskipTests

      - name: Use Minikube Docker daemon
        run: eval $(minikube docker-env)

      - name: Build Docker image for order-service
        run: |
          cd order-service
          docker build --no-cache -t order-service:latest .

      - name: Force K8s to use new image
        run: kubectl rollout restart deployment order-deployment

      - name: Deploy to Minikube
        run: |
          kubectl apply -f order-service/order-deployment.yml
          kubectl apply -f order-service/order-service.yml
