name: Deploy eureka Service to Minikube

on:
  workflow_dispatch:  # Enables manual trigger from any branch
  push:
    paths:
      - 'eureka-server/**'
      - 'order-service-ci-cd.yml'
    branches:
      - kubernates-deployment-fix

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Local runner with minikube & docker installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build eureka-service JAR
        run: |
          cd eureka-service
          mvn clean package -DskipTests

      - name: Use Minikube Docker daemon
        run: eval $(minikube docker-env)

      - name: Build Docker image for eureka-service
        run: |
          cd eureka-service
          docker build --no-cache -t eureka-server:latest .

      - name: Force K8s to use new image
        run: kubectl rollout restart deployment eureka-deployment

      - name: Deploy to Minikube
        run: |
          kubectl apply -f eureka-service/eureka-deployment.yml
          kubectl apply -f eureka-service/eureka-service.yml
